[tools]
python = "3.12" # [optional] will be used for the venv

[env]
# _.python.venv = ".venv" # relative to this file's directory
# _.python.venv = "/root/.venv" # can be absolute
# _.python.venv = "{{env.HOME}}/.cache/venv/myproj" # can use templates
_.python.venv = { path = ".venv", create = true } # create the venv if it doesn't exist
